export interface CaseRef {
  id: string;
  strategyId: string;
  name: string;
  location: string;
  year: string;
  architect: string;
  highlight: string;
  /** 主图地址；重配后为 gooood 图，未命中时为 wiki 图 */
  image: string;
  /** 原 wiki 图地址，作为最终回退（主图与本地图都取不到时使用） */
  imageWiki?: string;
}

export const cases: CaseRef[] = [
  { id: 'ch2-melbourne', strategyId: 'passive-design', name: 'Council House 2 (CH2)', location: '澳大利亚 墨尔本', year: '2006', architect: 'DesignInc', highlight: '全球最早的六星绿色写字楼之一，夜间蓄冷、相变材料与水回收闭环', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/CouncilHouse2.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/CouncilHouse2.jpg' },
  { id: 'bedzed', strategyId: 'passive-design', name: 'BedZED 零碳社区', location: '英国 伦敦', year: '2002', architect: 'Bill Dunster Architects', highlight: '英国首个大规模碳中和混合社区，风帽通风与热电联产系统', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/BedZED_2007.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/BedZED_2007.jpg' },
  { id: 'bosco-verticale', strategyId: 'vertical-greenery', name: '垂直森林 Bosco Verticale', location: '意大利 米兰', year: '2014', architect: 'Boeri Studio', highlight: '两座塔立面承载逾 2 万株植物，相当于把两公顷森林搬上天空', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bosco_Verticale_Milano.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bosco_Verticale_Milano.jpg' },
  { id: 'parkroyal-pickering', strategyId: 'vertical-greenery', name: '皮克林宾乐雅酒店', location: '新加坡', year: '2013', architect: 'WOHA', highlight: '层层退台承载 1.5 万㎡ 空中花园，绿化面积相当于整个用地', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/PARKROYAL_on_Pickering_(8134682524).jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/PARKROYAL_on_Pickering_(8134682524).jpg?width=1200' },
  { id: 'qunli-wetland', strategyId: 'sponge-city', name: '群力雨洪公园', location: '中国 哈尔滨', year: '2010', architect: '土人设计 Turenscape', highlight: '用外围蓄渗湿地把内涝小区海绵化，雨洪调蓄与公共游憩合一', image: 'https://oss.gooood.cn/uploads/2013/05/_c_xPf02x4XZjiSRJJV25Q1mpKrEN4UReUoX7p8Ijni7RdexXLQ8A4ShU_4mOiwivcmFkVqldlWWa-p5QOGSSUE1j_C5Rn7mCJA.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Qunli_National_Urban_Wetland_Park.jpg?width=1200' },
  { id: 'houtan-park', strategyId: 'sponge-city', name: '后滩湿地公园', location: '中国 上海', year: '2009', architect: '土人设计 Turenscape', highlight: '工业滩涂改造为梯级净水湿地，日处理受污染河水 2400 吨', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Houtan_Park_Shanghai.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Houtan_Park_Shanghai.jpg?width=1200' },
  { id: 'copenhill', strategyId: 'bipv', name: 'CopenHill 垃圾发电厂', location: '丹麦 哥本哈根', year: '2019', architect: 'BIG', highlight: '废物发电厂顶部是滑雪坡与徒步步道，立面光伏持续产能', image: 'https://oss.gooood.cn/uploads/2019/10/1-copenhill-amager-bakke-by-big.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Amager_Bakke.jpg' },
  { id: 'solar-siedlung', strategyId: 'bipv', name: '沃邦太阳船社区', location: '德国 弗莱堡', year: '2004', architect: 'Rolf Disch', highlight: '全球首批正产能住宅，屋顶光伏年发电量超过住户能耗', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Solarschiff_Solarsiedlung_Freiburg_im_Breisgau_september_2014.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Solarschiff_Solarsiedlung_Freiburg_im_Breisgau_september_2014.jpg?width=1200' },
  { id: 'eastgate-centre', strategyId: 'wind-corridor', name: 'Eastgate 购物中心', location: '津巴布韦 哈拉雷', year: '1996', architect: 'Mick Pearce', highlight: '仿白蚁冢的自然通风蓄热综合体，常规空调能耗降低约 90%', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Eastgate_Centre,_Harare,_Zimbabwe.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Eastgate_Centre,_Harare,_Zimbabwe.jpg' },
  { id: 'bahrain-wtc', strategyId: 'wind-corridor', name: '巴林世界贸易中心', location: '巴林 麦纳麦', year: '2008', architect: 'Atkins', highlight: '首座将三台大型风力涡轮架入双塔风帆之间的摩天楼', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bahrain_WTC.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bahrain_WTC.jpg' },
  { id: 'japan-pavilion-2000', strategyId: 'light-build', name: '汉诺威世博会日本馆', location: '德国 汉诺威', year: '2000', architect: '坂茂 Shigeru Ban', highlight: '纸筒编织的 70 米网格拱壳，展后纸材全部回收再利用', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Japanese_Pavilion,_Expo_2000,_Hannover.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Japanese_Pavilion,_Expo_2000,_Hannover.jpg?width=1200' },
  { id: 'cardboard-cathedral', strategyId: 'light-build', name: '纸板大教堂', location: '新西兰 基督城', year: '2013', architect: '坂茂 Shigeru Ban', highlight: '震后仅用 11 个月建成的纸管应急圣殿，轻量而庄重', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Christchurch_Cardboard_Cathedral_1_(31310889165).jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Christchurch_Cardboard_Cathedral_1_(31310889165).jpg' },
  { id: 'suzhou-museum', strategyId: 'courtyard-embed', name: '苏州博物馆', location: '中国 苏州', year: '2006', architect: '贝聿铭 I. M. Pei', highlight: '片石假山与几何院落延续苏州园林精神，光影经营至极', image: 'https://oss.gooood.cn/uploads/2021/10/19-Suzhou-Museum-West-by-gmp.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Suzhou_Museum,_China_(2015)_-_05.jpg' },
  { id: 'mia-doha', strategyId: 'courtyard-embed', name: '伊斯兰艺术博物馆', location: '卡塔尔 多哈', year: '2008', architect: '贝聿铭 I. M. Pei', highlight: '海上孤岛建筑，以中庭、庭院与水景组织光与几何', image: 'https://oss.gooood.cn/uploads/2017/03/MIA-PEI-YJL-2.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Museum_of_Islamic_Art,_Doha_00_(54).jpg' },
  { id: 'villa-savoye', strategyId: 'pilotis', name: '萨伏伊别墅', location: '法国 普瓦西', year: '1931', architect: '勒·柯布西耶', highlight: '底层架空定义现代建筑五原则，屋顶花园与自由平面', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/VillaSavoye.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/VillaSavoye.jpg' },
  { id: 'unite-habitation', strategyId: 'pilotis', name: '马赛公寓', location: '法国 马赛', year: '1952', architect: '勒·柯布西耶', highlight: '巨柱托起一座垂直花园城市，架空层释放场地', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cité_radieuse,_Marseille.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cité_radieuse,_Marseille.jpg?width=1200' },
  { id: 'nezu-museum', strategyId: 'gray-space', name: '根津美术馆', location: '日本 东京', year: '2009', architect: '隈研吾 Kengo Kuma', highlight: '大屋檐下竹林廊道消隐建筑与庭园的边界', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/2018_Nezu_Museum_1.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/2018_Nezu_Museum_1.jpg' },
  { id: 'koshino-house', strategyId: 'gray-space', name: '小筱邸', location: '日本 芦屋', year: '1984', architect: '安藤忠雄', highlight: '混凝土长墙框出院落与廊道，阴翳成为空间主角', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Koshino_House.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Koshino_House.jpg?width=1200' },
  { id: 'habitat-67', strategyId: 'terrace-step', name: 'Habitat 67', location: '加拿大 蒙特利尔', year: '1967', architect: 'Moshe Safdie', highlight: '354 个预制箱体堆叠出错落的空中花园住宅群落', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Habitat_67,_southwest_view.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Habitat_67,_southwest_view.jpg' },
  { id: 'interlace', strategyId: 'terrace-step', name: '翠城新馨 The Interlace', location: '新加坡', year: '2013', architect: 'OMA / Ole Scheeren', highlight: '31 栋住宅水平交错堆叠，重构高密度居住的退台与花园', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Interlace,_Singapore.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Interlace,_Singapore.jpg' },
  { id: 'ford-foundation', strategyId: 'atrium-core', name: '福特基金会总部', location: '美国 纽约', year: '1967', architect: 'Kevin Roche / John Dinkeloo', highlight: '最早把 12 层室内庭院作为组织核心的办公建筑', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Interior-Ford_Foundation-01.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Interior-Ford_Foundation-01.jpg' },
  { id: 'sony-center', strategyId: 'atrium-core', name: '索尼中心', location: '德国 柏林', year: '2000', architect: 'Murphy/Jahn', highlight: '巨型织物顶篷覆盖向城市开放的公共中庭，日夜变色', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sony_Center_Berlin.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sony_Center_Berlin.jpg' },
  { id: 'edge-amsterdam', strategyId: 'shared-floor', name: 'The Edge 办公楼', location: '荷兰 阿姆斯特丹', year: '2014', architect: 'PLP Architecture', highlight: '大平层布局结合两万多传感器，重塑协同办公效率', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/TheEdge_03-2024.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/TheEdge_03-2024.jpg' },
  { id: 'bloomberg-london', strategyId: 'shared-floor', name: '彭博欧洲总部', location: '英国 伦敦', year: '2017', architect: 'Foster + Partners', highlight: '整层无柱协同空间，铜鳍天花整合送风与声学', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bloomberg_London_exterior_-_Cannon_Street,_Walbrook.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bloomberg_London_exterior_-_Cannon_Street,_Walbrook.jpg' },
  { id: 'new-gourna', strategyId: 'local-material', name: '新高纳村', location: '埃及 卢克索', year: '1945', architect: 'Hassan Fathy', highlight: '以土坯拱穹与村民共建复兴在地建造体系', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/New_Gourna.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/New_Gourna.jpg' },
  { id: 'gando-school', strategyId: 'local-material', name: '甘多小学', location: '布基纳法索 甘多', year: '2001', architect: 'Francis Kéré', highlight: '压缩土砖、悬挑铁皮屋面与全村参与的在地营造', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gando-School-Burkina-Faso.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gando-School-Burkina-Faso.jpg' },
  { id: 'harbin-opera', strategyId: 'symbol-translate', name: '哈尔滨大剧院', location: '中国 哈尔滨', year: '2015', architect: 'MAD Architects', highlight: '以冰雪风蚀与自然等高线转译北国地域气质', image: 'https://oss.gooood.cn/uploads/2017/08/1-harbin-opera-house_kris-provoost.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Harbin_Grand_Theatre_Pano_201609.jpg' },
  { id: 'heydar-center', strategyId: 'symbol-translate', name: '盖达尔·阿利耶夫中心', location: '阿塞拜疆 巴库', year: '2012', architect: 'Zaha Hadid Architects', highlight: '从地面翻起的连续曲面折叠出地域与未来的对话', image: 'https://oss.gooood.cn/uploads/2013/11/_c_Zy7I8OKFFUknlvkI4BVfQW5cxREYuQI6XnHeBhG3m-mZDcEy12G-RUsKzXpiFTLrApwW8J8ghvJ6Ik9tE7LLqESe_paKf_uc.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Heydar_Aliyev_Center_in_Baku_in_Azerbaijan.jpg' },
  { id: 'tate-modern', strategyId: 'memory-retain', name: '泰特现代美术馆', location: '英国 伦敦', year: '2000', architect: 'Herzog & de Meuron', highlight: '河岸发电厂重生，工业尺度成为当代艺术的容器', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tate_Modern_-_Bankside_Power_Station.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tate_Modern_-_Bankside_Power_Station.jpg' },
  { id: 'zeitz-mocaa', strategyId: 'memory-retain', name: '蔡茨非洲当代艺术博物馆', location: '南非 开普敦', year: '2017', architect: 'Heatherwick Studio', highlight: '在历史谷仓 42 根混凝土筒仓中雕刻出中庭与展厅', image: 'https://oss.gooood.cn/uploads/2017/09/001-Zeitz-MOCAA-by-Heatherwick-studio.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Zeitz_Museum_of_Contemporary_Art_Africa,_Cape_Town_(_1050775).jpg' },
  { id: 'superkilen', strategyId: 'micro-weave', name: 'Superkilen 公园', location: '丹麦 哥本哈根', year: '2012', architect: 'BIG / Topotek1 / Superflex', highlight: '一公里线性公园用六十余国日常物件织补多元社区', image: 'https://oss.gooood.cn/uploads/2012/10/_c_ERqXdw1xmvb7UzVIYZZy-KAkkAHjISWvr7Ro528wO18PzZN90cbplE29cYweTKdj37ZkBO4g2zLweTztUgMl9Btsd81_n2Ha.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Superkilen_hill-top_view.jpg' },
  { id: 'cheonggyecheon', strategyId: 'micro-weave', name: '清溪川复原工程', location: '韩国 首尔', year: '2005', architect: '首尔市政府', highlight: '拆除高架道路复原河道，缝合被切断半个世纪的城市', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cheonggyecheon_evening_2.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cheonggyecheon_evening_2.jpg' },
  { id: 'al-bahr', strategyId: 'climate-form', name: 'Al Bahr 双塔', location: '阿联酋 阿布扎比', year: '2012', architect: 'Aedas', highlight: '千扇动态三角木格屏随阳光轨迹智能开合', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Fountain_and_Al_Bahr_Towers_-_panoramio.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Fountain_and_Al_Bahr_Towers_-_panoramio.jpg' },
  { id: 'masdar', strategyId: 'climate-form', name: '马斯达尔学院', location: '阿联酋 阿布扎比', year: '2010', architect: 'Foster + Partners', highlight: '窄巷、风塔与高密度形制再现沙漠聚落的气候智慧', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Masdar_City_under_construction_2012.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Masdar_City_under_construction_2012.jpg?width=1200' },
  { id: 'the-shard', strategyId: 'vertical-mix', name: '碎片大厦', location: '英国 伦敦', year: '2012', architect: 'Renzo Piano Building Workshop', highlight: '玻璃尖塔内垂直叠合办公、酒店、居住与观景', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Shard_at_sunset_2017_(cropped).jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Shard_at_sunset_2017_(cropped).jpg' },
  { id: 'azabudai-hills', strategyId: 'vertical-mix', name: '麻布台之丘', location: '日本 东京', year: '2023', architect: 'Heatherwick Studio', highlight: '低层绿谷与超塔编织的立体花园城市', image: 'https://oss.gooood.cn/uploads/2024/03/004-azabudai-hills-by-pelli-clarke-partners.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Azabudai_Hills_opening_day_19.jpg' },
  { id: '798-district', strategyId: 'time-evolve', name: '798 艺术区', location: '中国 北京', year: '2002', architect: '厂区自主更新', highlight: '包豪斯风格军工厂房时序演化为当代艺术聚落', image: 'https://oss.gooood.cn/uploads/2021/05/017-mg-space-china-by-studio-hvn.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Beijing_798_Art_District.jpg' },
  { id: 'distillery-district', strategyId: 'time-evolve', name: '古酿酒厂区', location: '加拿大 多伦多', year: '2003', architect: 'ERA Architects', highlight: '维多利亚威士忌厂区按时段活化成文创街区', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/GooderhamAndWorts1800s.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/GooderhamAndWorts1800s.jpg' },
  { id: 'rolex-learning', strategyId: 'boundary-penetrate', name: '劳力士学习中心', location: '瑞士 洛桑', year: '2010', architect: 'SANAA', highlight: '起伏地景上的孔洞与缓坡让校园边界自由流动', image: 'https://oss.gooood.cn/uploads/2012/03/4e5f49374f5c5881c88a6b3a96b6da5a.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rolex_Learning_center.jpg' },
  { id: 'yokohama-terminal', strategyId: 'boundary-penetrate', name: '横滨国际客运码头', location: '日本 横滨', year: '2002', architect: 'Foreign Office Architects', highlight: '折叠地表把码头屋面变成可穿越的城市广场', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ōsanbashi_Pier.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ōsanbashi_Pier.jpg?width=1200' },
  { id: 'roppongi-hills', strategyId: 'vitality-ring', name: '六本木之丘', location: '日本 东京', year: '2003', architect: '森ビル / Jerde', highlight: '职住商娱一体的全天候垂直城中城', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Roppongi_Hills_2013-12-01.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Roppongi_Hills_2013-12-01.jpg' },
  { id: 'xintiandi', strategyId: 'vitality-ring', name: '上海新天地', location: '中国 上海', year: '2001', architect: 'Wood + Zapata / 同济大学', highlight: '石库门里弄里日夜交替的餐饮零售活力街区', image: 'https://oss.gooood.cn/uploads/2025/07/002-shanghai-xintiandi-design-festival-mirage-by-mars.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Xintiandi5.jpg' },
  { id: 'seattle-library', strategyId: 'public-return', name: '西雅图中央图书馆', location: '美国 西雅图', year: '2004', architect: 'OMA / LMN', highlight: '螺旋书库与城市客厅式的全开放公共空间', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Seattle_Library_01.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Seattle_Library_01.jpg' },
  { id: 'sendai-mediatheque', strategyId: 'public-return', name: '仙台媒体中心', location: '日本 仙台', year: '2001', architect: '伊东丰雄', highlight: '海草般的管柱支撑起通透如水面的公共媒体之盒', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sendai_Mediatheque_2009.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sendai_Mediatheque_2009.jpg' },
  { id: 'nakagin', strategyId: 'modular-build', name: '中银胶囊塔', location: '日本 东京', year: '1972', architect: '黑川纪章', highlight: '140 个可更换居住舱体组成的代谢派宣言', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nakagin_Capsule_Tower_(51472766807).jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nakagin_Capsule_Tower_(51472766807).jpg' },
  { id: 'brock-commons', strategyId: 'modular-build', name: 'Brock Commons 木构学生公寓', location: '加拿大 温哥华', year: '2017', architect: 'Acton Ostry Architects', highlight: '18 层重型木结构以预制模块快速装配封顶', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Brock_Commons.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Brock_Commons.jpg?width=1200' },
  { id: 'hsbc-hk', strategyId: 'core-skin', name: '汇丰银行总行大厦', location: '中国 香港', year: '1985', architect: 'Foster + Partners', highlight: '结构外挂释放底层，模数化悬挂层办公自由可变', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/HK_HSBC_Main_Building_2008_(cropped).jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/HK_HSBC_Main_Building_2008_(cropped).jpg' },
  { id: 'hearst-tower', strategyId: 'core-skin', name: '赫斯特大厦', location: '美国 纽约', year: '2006', architect: 'Foster + Partners', highlight: '历史石楼上升起三角网格 diagrid 自由表皮', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Hearst_Tower_(August_2024).jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Hearst_Tower_(August_2024).jpg' },
  { id: '461-dean', strategyId: 'prefab', name: '461 Dean 公寓', location: '美国 纽约', year: '2015', architect: 'SHoP Architects', highlight: '建成时全球最高的预制模块住宅之一，900 余个模块现场拼装', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/461Dean_construction.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/461Dean_construction.jpg?width=1200' },
  { id: 'the-stack', strategyId: 'prefab', name: 'The Stack 公寓', location: '美国 纽约', year: '2014', architect: 'GLUCK+', highlight: '56 个模块叠合，主体结构一周内装配完成', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Stack_4857.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Stack_4857.jpg?width=1200' },
  { id: 'centre-pompidou', strategyId: 'structure-space', name: '蓬皮杜中心', location: '法国 巴黎', year: '1977', architect: 'Renzo Piano + Richard Rogers', highlight: '结构与设备全部外挂，室内得到完全自由的大空间', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pompidou_center.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pompidou_center.jpg' },
  { id: 'sainsbury-centre', strategyId: 'structure-space', name: '塞恩斯伯里视觉艺术中心', location: '英国 诺维奇', year: '1978', architect: 'Foster + Partners', highlight: '单一跨距桁架把结构、设备、走廊与展厅整合为一体', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sainsbury_Centre_building_with_rainbow.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sainsbury_Centre_building_with_rainbow.jpg' },
  { id: 'diagoon', strategyId: 'growth-frame', name: 'Diagoon 骨架住宅', location: '荷兰 代尔夫特', year: '1971', architect: 'Herman Hertzberger', highlight: '只提供结构骨架与平台，留出一半让居住者自行生长', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Diagoon_Delft.jpg?width=1200', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Diagoon_Delft.jpg?width=1200' },
  { id: 'quinta-monroy', strategyId: 'growth-frame', name: '金塔蒙罗伊住宅', location: '智利 伊基克', year: '2004', architect: 'Alejandro Aravena', highlight: '只建造“一半的好房子”，住户可在框架内续建增值', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Quinta_Monroy_Infill_Diagram.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Quinta_Monroy_Infill_Diagram.jpg' },
  { id: 'federation-square', strategyId: 'facade-vitality', name: '联邦广场', location: '澳大利亚 墨尔本', year: '2002', architect: 'LAB Architecture Studio', highlight: '三角碎石立面下全天候活跃的市民文化客厅', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Fed_Square,_Melbourne,_west_view_20230219_1.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Fed_Square,_Melbourne,_west_view_20230219_1.jpg' },
  { id: 'taikoo-li', strategyId: 'facade-vitality', name: '三里屯太古里', location: '中国 北京', year: '2008', architect: 'Oval Partnership', highlight: '开放式胡同院落与通透橱窗构成连续活跃界面', image: 'https://oss.gooood.cn/uploads/2026/05/008-sanlitun-north-district-urban-renewal-by-china-academy-of-building-research.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/三里屯太古里南区.jpg' },
  { id: 'millennium-park', strategyId: 'urban-public-space', name: '千禧公园', location: '美国 芝加哥', year: '2004', architect: 'Gehry / Gustafson 等', highlight: '铁路车场盖上建成世界级城市公共艺术公园', image: 'https://oss.gooood.cn/uploads/2026/09/014-Lurie-Garden-at-Millennium-Park.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Millennium_Square,_Chicago,_Illinois_(9181701264).jpg' },
  { id: 'zaryadye', strategyId: 'urban-public-space', name: '扎里亚季耶公园', location: '俄罗斯 莫斯科', year: '2017', architect: 'Diller Scofidio + Renfro', highlight: '四片野生地景覆盖红场旁的覆土文化场馆', image: 'https://oss.gooood.cn/uploads/2019/11/053-zaryadye-park-by-diller-scofidio-renfro.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Zaryadye25.jpg' },
  { id: 'high-line', strategyId: 'slow-stitch', name: '高线公园', location: '美国 纽约', year: '2009', architect: 'Field Operations / DS+R', highlight: '废弃高架铁路转化为悬浮慢行绿道，缝合西区街区', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/AHigh_Line_Park,_Section_1a.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/AHigh_Line_Park,_Section_1a.jpg' },
  { id: 'seoullo-7017', strategyId: 'slow-stitch', name: '首尔路 7017', location: '韩国 首尔', year: '2017', architect: 'MVRDV', highlight: '高架路桥转化为一公里空中花园步行街', image: 'https://oss.gooood.cn/uploads/2017/05/002-Seoul-Skygarden.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Seoullo_7017_Overview_(5).jpg' },
  { id: 'axe-historique', strategyId: 'view-corridor', name: '巴黎历史轴', location: '法国 巴黎', year: '17–20 世纪', architect: '勒·诺特 / 奥斯曼 等', highlight: '从卢浮宫经凯旋门至拉德芳斯的城市视轴通廊', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jardin_des_Tuileries_Axis_Historique.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jardin_des_Tuileries_Axis_Historique.jpg' },
  { id: 'national-mall', strategyId: 'view-corridor', name: '国家广场', location: '美国 华盛顿', year: '1902', architect: '麦克米兰规划委员会', highlight: '纪念碑群与开阔草坪构成国家纪念性视线通廊', image: 'https://oss.gooood.cn/uploads/2021/04/017-2020-asla-general-design-award-of-honor-designing-implementing-and-managing-improvements-to-the-national-mall-hok.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/National_Mall,_Washington,_D.C._(20100325-DSC01310).jpg' },
  { id: 'snfcc', strategyId: 'gradient-open', name: '斯塔弗洛斯·尼阿乔斯文化中心', location: '希腊 雅典', year: '2016', architect: 'Renzo Piano Building Workshop', highlight: '抬升草坡把场馆渐变融入海岸，屋顶与海平面齐平', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Stavros_Niarchos_Foundation_Cultural_Center_-_52035330487.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/Stavros_Niarchos_Foundation_Cultural_Center_-_52035330487.jpg' },
  { id: 'va-dundee', strategyId: 'gradient-open', name: 'V&A 邓迪博物馆', location: '英国 邓迪', year: '2018', architect: '隈研吾 Kengo Kuma', highlight: '仿苏格兰悬崖与船体的曲面把城市与水岸渐变缝合', image: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_RRS_Discovery_&_the_V&A_Museum,_Dundee.jpg', imageWiki: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_RRS_Discovery_&_the_V&A_Museum,_Dundee.jpg' },
];

const caseMap: Map<string, CaseRef[]> = new Map();
for (const c of cases) {
  const list = caseMap.get(c.strategyId) ?? [];
  list.push(c);
  caseMap.set(c.strategyId, list);
}

export function getCasesByStrategy(strategyId: string): CaseRef[] {
  return caseMap.get(strategyId) ?? [];
}
